import type { HelpArticle } from './types';

/** Risque & règles — how risk is computed, decided, and proved. */
export const RISQUE_ARTICLES: readonly HelpArticle[] = [
  {
    id: 'HLP-030',
    slug: 'dll-vs-perte-maximale',
    category: 'risque-regles',
    title: 'Perte quotidienne et perte maximale : ne pas les confondre',
    summary:
      'Deux règles, deux portées, deux conséquences. L’une ferme la journée, l’autre ferme le compte.',
    status: 'publish',
    severity: 'information',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'risk engine'],
    searchAliases: ['dll', 'mll', 'difference', 'confusion', 'drawdown'],
    related: ['perte-quotidienne', 'perte-maximale-eod', 'permissions-de-trading'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'table',
        caption: 'Les deux règles côte à côte',
        columns: ['Critère', 'Perte quotidienne', 'Perte maximale'],
        rows: [
          ['Portée', 'La journée', 'Toute la durée du compte'],
          ['Type', 'Blocage temporaire', 'Compte terminé'],
          ['Réversible', 'Au reset serveur, si autorisé', 'Non'],
          ['Nouvelles expositions', 'Bloquées jusqu’au reset', 'Bloquées définitivement'],
          ['Compte terminé', 'Non', 'Oui'],
        ],
      },
      { kind: 'heading', text: 'Les valeurs en vigueur' },
      { kind: 'ruleTable', facts: ['dailyLossRate', 'maximumLossRate'] },
      {
        kind: 'callout',
        tone: 'attention',
        title: 'Une même journée peut approcher les deux',
        text: 'Le moteur retourne les permissions exactes. L’interface ne déduit jamais vos droits d’une couleur ou d’un pourcentage.',
      },
    ],
  },
  {
    id: 'HLP-031',
    slug: 'trailing-eod',
    category: 'risque-regles',
    title: 'Comment fonctionne le trailing EOD ?',
    summary:
      'Le plancher se réévalue à la fin d’une journée finalisée, pas à chaque tick positif. Et il ne redescend jamais.',
    status: 'publish',
    severity: 'hard_breach',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'risk engine'],
    searchAliases: ['eod', 'trailing', 'plancher', 'floor', 'drawdown trailing'],
    related: ['perte-maximale-eod', 'reset-limites-quotidiennes', 'dll-vs-perte-maximale'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: '**EOD** signifie que le plancher de perte maximale peut être réévalué à la fin d’une journée finalisée, plutôt qu’en suivant chaque profit latent intraday.',
      },
      { kind: 'heading', text: 'Principes' },
      {
        kind: 'list',
        items: [
          'le montant de risque est déterminé par la policy ;',
          'un nouveau plus haut EOD pertinent peut relever le plancher ;',
          'un jour moins profitable ne fait pas redescendre un plancher déjà acquis ;',
          'le plancher publié par le serveur est la vérité.',
        ],
      },
      {
        kind: 'paragraph',
        text: 'L’intérêt de cette règle est que la progression du plancher est liée à des journées finalisées, pas à un pic intraday que le marché reprend une heure plus tard. Votre Hub affiche le plancher actuel et l’espace restant.',
      },
    ],
  },
  {
    id: 'HLP-032',
    slug: 'reset-limites-quotidiennes',
    category: 'risque-regles',
    title: 'Quand les limites quotidiennes sont-elles réinitialisées ?',
    summary:
      'À une frontière serveur fondée sur UTC. Recharger le navigateur ne débloque jamais un compte.',
    status: 'dynamic',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['risk engine', 'domain code'],
    searchAliases: ['reset', 'minuit', 'utc', 'heure', 'debloquer', 'journee'],
    related: ['perte-quotidienne', 'permissions-de-trading'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'WARIBA utilise une référence temporelle serveur fondée sur UTC. Le serveur fournit le prochain instant de reset, qui est ensuite affiché dans votre fuseau, avec l’heure UTC disponible.',
      },
      {
        kind: 'callout',
        tone: 'attention',
        title: 'Recharger ne débloque rien',
        text: 'Après un blocage quotidien, le retour à un état tradable dépend du reset serveur et d’une nouvelle évaluation des règles. Rafraîchir la page ne change aucun état.',
      },
      {
        kind: 'paragraph',
        text: 'C’est aussi pourquoi l’interface n’affiche jamais « minuit » sans contexte : minuit chez vous et la frontière de journée du programme ne sont pas nécessairement le même instant.',
      },
    ],
  },
  {
    id: 'HLP-033',
    slug: 'permissions-de-trading',
    category: 'risque-regles',
    title: 'Comment les permissions de trading sont-elles décidées ?',
    summary:
      'Le serveur fournit des permissions explicites. WariX ne les déduit jamais d’un statut visuel.',
    status: 'publish',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['risk engine', 'domain code'],
    searchAliases: ['permission', 'autorise', 'bloque', 'interdit', 'droits'],
    related: ['perte-quotidienne', 'ordre-refuse', 'warix-deconnexion'],
    lastReviewedAt: '2026-08-24',
    body: [
      { kind: 'heading', text: 'Les permissions que le serveur décide' },
      {
        kind: 'list',
        items: [
          'ouvrir une exposition ;',
          'augmenter une exposition ;',
          'réduire ;',
          'clôturer ;',
          'placer un ordre en attente ;',
          'annuler un ordre en attente.',
        ],
      },
      {
        kind: 'example',
        title: 'Pourquoi ces permissions ne sont pas un seul interrupteur',
        lines: [
          'pendant un blocage quotidien, ouvrir une nouvelle exposition est interdit ;',
          'clôturer une position, ce qui réduit le risque, peut rester permis.',
        ],
        conclusion:
          'Un unique état « bloqué » vous empêcherait de sortir d’une position au moment où c’est le plus utile.',
      },
      {
        kind: 'paragraph',
        text: 'Si votre terminal se reconnecte après une coupure, il resynchronise l’état autoritatif avant de réactiver les actions sensibles.',
      },
    ],
  },
  {
    id: 'HLP-034',
    slug: 'instruments-et-exposition',
    category: 'risque-regles',
    title: 'Instruments, tailles et exposition maximale',
    summary:
      'Le catalogue d’instruments et les limites d’exposition sont des données de policy, pas du texte figé.',
    status: 'dynamic',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['symbol specifications', 'published_account_policy'],
    searchAliases: ['instruments', 'symboles', 'eurusd', 'xauusd', 'nas100', 'lot', 'exposition'],
    related: ['frais-de-trading', 'ordre-refuse', 'placer-un-ordre'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'Le périmètre V1 actuellement verrouillé comprend EURUSD, GBPUSD, USDJPY, XAUUSD et NAS100.',
      },
      { kind: 'heading', text: 'Ce que la spécification publie pour chaque symbole' },
      {
        kind: 'list',
        items: [
          'précision de prix ;',
          'taille minimale ;',
          'taille de contrat ;',
          'heures de marché ;',
          'limites de taille et d’exposition ;',
          'spread, commission et swap applicables.',
        ],
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Ces valeurs ne sont pas recopiées ici',
        text: 'Elles vivent dans les spécifications de symboles publiées et sont affichées dans WariX pour l’instrument sélectionné. Une valeur encore candidate n’est pas affichée comme règle publique.',
      },
    ],
  },
  {
    id: 'HLP-035',
    slug: 'frais-de-trading',
    category: 'risque-regles',
    title: 'Spread, slippage, commissions et swaps',
    summary: 'Quatre éléments qui influencent le P&L, l’equity — et donc votre risque.',
    status: 'dynamic',
    severity: 'information',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['symbol specifications'],
    searchAliases: ['spread', 'slippage', 'commission', 'swap', 'frais', 'cout'],
    related: ['instruments-et-exposition', 'stop-loss-take-profit', 'solde-et-equity'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'table',
        columns: ['Élément', 'Ce que c’est'],
        rows: [
          ['Spread', 'Écart entre prix acheteur et prix vendeur.'],
          [
            'Slippage',
            'Différence possible entre le prix observé et le prix réellement exécuté, selon le modèle serveur.',
          ],
          ['Commission', 'Frais de transaction lorsque la spécification en prévoit.'],
          [
            'Swap',
            'Ajustement lié au maintien de certaines positions, selon l’instrument et le modèle.',
          ],
        ],
      },
      {
        kind: 'callout',
        tone: 'attention',
        title: 'Ils comptent dans le risque',
        text: 'Ces éléments modifient le P&L et donc l’equity, qui est la valeur surveillée par les règles de risque. Les montants exacts viennent des spécifications publiées : WARIBA n’affiche pas des frais nuls par défaut.',
      },
    ],
  },
  {
    id: 'HLP-036',
    slug: 'ordre-refuse',
    category: 'risque-regles',
    title: 'Pourquoi un ordre peut-il être refusé ?',
    summary:
      'Un refus signifie que le serveur n’a pas accepté l’action. Aucun fill n’est créé et aucune position ne bouge.',
    status: 'publish',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['risk engine', 'domain code'],
    searchAliases: ['refuse', 'rejected', 'rejet', 'erreur ordre', 'impossible'],
    related: ['permissions-de-trading', 'donnees-de-marche', 'placer-un-ordre'],
    lastReviewedAt: '2026-08-24',
    body: [
      { kind: 'heading', text: 'Raisons possibles' },
      {
        kind: 'list',
        items: [
          'compte non tradable ;',
          'perte quotidienne atteinte ;',
          'perte maximale dépassée ;',
          'exposition maximale atteinte ;',
          'prix trop ancien pour exécuter ;',
          'marché fermé ;',
          'ordre invalide ;',
          'connexion pas encore resynchronisée ;',
          'ressource non autorisée.',
        ],
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Un refus ne laisse aucune trace financière',
        text: 'Un ordre refusé ne crée pas de fill, n’augmente aucune position et ne modifie pas le ledger.',
      },
      {
        kind: 'paragraph',
        text: 'WariX affiche un message persistant lorsque le refus demande une action, avec un code stable et une référence support lorsqu’elle existe. Lisez la raison plutôt que de renvoyer la même commande plusieurs fois.',
      },
    ],
  },
  {
    id: 'HLP-037',
    slug: 'donnees-de-marche',
    category: 'risque-regles',
    title: 'Données de marché : à jour, obsolètes, hors ligne',
    summary:
      'Quand les prix ne sont pas assez récents pour ouvrir une exposition, le serveur refuse l’action plutôt que d’exécuter contre un prix ancien.',
    status: 'publish',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['domain code', 'realtime service'],
    searchAliases: ['stale', 'offline', 'deconnecte', 'prix', 'obsolete', 'resync'],
    related: ['warix-deconnexion', 'graphique-et-execution', 'ordre-refuse'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'table',
        columns: ['État', 'Ce qu’il signifie'],
        rows: [
          ['À jour', 'Les prix sont suffisamment récents pour exécuter.'],
          ['Obsolète (stale)', 'Les données sont trop anciennes pour ouvrir une exposition.'],
          ['Hors ligne', 'La connexion au flux est perdue.'],
          [
            'Resynchronisation',
            'Le terminal récupère l’état autoritatif avant de réactiver les actions.',
          ],
        ],
      },
      {
        kind: 'paragraph',
        text: 'Après une reconnexion, WariX ne suppose pas que les anciennes permissions sont encore valides. Il récupère un instantané autoritatif et les événements nécessaires avant de réactiver les commandes.',
      },
    ],
  },
  {
    id: 'HLP-038',
    slug: 'pratiques-autorisees-et-interdites',
    category: 'risque-regles',
    title: 'Pratiques autorisées et interdites',
    summary:
      'Publié seulement quand chaque pratique aura sa définition, ses critères de preuve et son recours.',
    status: 'draft_policy',
    blockedBy: 'Définitions d’intégrité (hedging, EA, HFT, copy trading) — non publiées',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy'],
    searchAliases: ['interdit', 'autorise', 'hedging', 'ea', 'bot', 'hft', 'copy trading'],
    related: ['trading-integre'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'Cet article sera publié lorsque l’Account Policy définira précisément chaque pratique : définition, critère de preuve, conséquence et parcours de recours.',
      },
      {
        kind: 'paragraph',
        text: 'WARIBA ne recopiera pas les interdictions d’un concurrent. Une interdiction sans définition mesurable et sans recours est une décision arbitraire en attente.',
      },
    ],
  },
  {
    id: 'HLP-039',
    slug: 'trading-integre',
    category: 'risque-regles',
    title: 'Trading intègre et exploitation technique',
    summary:
      'Une décision d’intégrité s’appuie sur une règle publiée et des faits audités — jamais sur une impression.',
    status: 'publish',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'Decision Log'],
    searchAliases: ['integrite', 'fraude', 'exploitation', 'bug', 'triche'],
    related: ['lire-preuve-breach', 'ouvrir-une-contestation'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'WARIBA évalue le comportement de trading dans un environnement simulé. Une performance obtenue en exploitant volontairement une erreur technique, une donnée manifestement incorrecte ou une incohérence du système peut faire l’objet d’une revue d’intégrité lorsque la policy le prévoit.',
      },
      { kind: 'heading', text: 'Ce qu’une décision d’intégrité doit porter' },
      {
        kind: 'list',
        items: [
          'une règle publiée ;',
          'des faits ;',
          'une période ;',
          'des références d’audit ;',
          'un code de raison ;',
          'un recours lorsque la décision est contestable.',
        ],
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Une stratégie inhabituelle n’est pas une preuve',
        text: 'Trader différemment de la moyenne n’est pas, en soi, un indice de fraude. Une décision d’intégrité opaque n’en est pas une.',
      },
    ],
  },
  {
    id: 'HLP-040',
    slug: 'lire-preuve-breach',
    category: 'risque-regles',
    title: 'Comment lire la preuve d’un breach ?',
    summary:
      'Ce que contient une preuve, et pourquoi l’originale n’est jamais supprimée quand vous la contestez.',
    status: 'publish',
    severity: 'hard_breach',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['risk engine', 'audit trail'],
    searchAliases: ['preuve', 'evidence', 'breach', 'justificatif', 'pourquoi'],
    related: ['limite-maximale-depassee', 'ouvrir-une-contestation', 'preuve-originale-conservee'],
    lastReviewedAt: '2026-08-24',
    body: [
      { kind: 'heading', text: 'Ce que contient une preuve' },
      {
        kind: 'list',
        items: [
          'la règle ;',
          'le seuil ;',
          'la valeur observée ;',
          'l’instant ;',
          'la version de policy ;',
          'le compte ;',
          'les ordres et exécutions pertinents ;',
          'les données de marché utilisées ;',
          'le correlation ID.',
        ],
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'La preuve originale est conservée',
        text: 'Une contestation ajoute un dossier et une décision. Elle ne supprime ni ne réécrit silencieusement l’événement initial.',
      },
    ],
  },
];
