import type { HelpArticle } from './types';

/** Risque & règles — how risk is computed, decided, and proved. */
export const RISQUE_ARTICLES: readonly HelpArticle[] = [
  {
    id: 'HLP-030',
    slug: 'dll-vs-perte-maximale',
    category: 'risque-regles',
    title: 'Quelle différence entre la perte quotidienne et la perte maximale ?',
    summary:
      'Deux limites, deux conséquences très différentes. L’une arrête votre journée. L’autre met fin à votre compte.',
    status: 'publish',
    severity: 'information',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'risk engine'],
    searchAliases: [
      'dll',
      'mll',
      'difference',
      'confusion',
      'drawdown',
      'daily loss',
      'max loss',
      'quelle limite',
    ],
    related: ['perte-quotidienne', 'perte-maximale-eod', 'permissions-de-trading'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'La perte quotidienne protège une seule journée : si vous l’atteignez, les nouvelles positions sont suspendues jusqu’au prochain reset. La perte maximale protège le compte dans la durée : son franchissement met fin au compte.',
      },
      { kind: 'visual', id: 'HLP-VIS-001' },
      {
        kind: 'table',
        caption: 'Les deux règles côte à côte',
        columns: ['Question', 'Perte quotidienne', 'Perte maximale'],
        rows: [
          ['Ce qu’elle protège', 'Votre journée', 'Votre compte, du début à la fin'],
          [
            'Ce qui se passe',
            'Vous ne pouvez plus ouvrir de position aujourd’hui',
            'Le compte est terminé',
          ],
          ['Est-ce réversible ?', 'Oui, au prochain reset', 'Non'],
          ['Le compte est-il perdu ?', 'Non', 'Oui'],
        ],
      },
      { kind: 'heading', text: 'Les limites en vigueur' },
      { kind: 'ruleTable', facts: ['dailyLossRate', 'maximumLossRate'] },
      {
        kind: 'callout',
        tone: 'attention',
        title: 'Les deux peuvent être touchées le même jour',
        text: 'Une mauvaise journée peut vous approcher des deux limites à la fois, mais elles ne font pas la même chose. La perte quotidienne arrête votre activité pour la journée. La perte maximale protège votre compte sur toute sa durée : c’est celle qui peut y mettre fin.',
      },
    ],
  },
  {
    id: 'HLP-031',
    slug: 'trailing-eod',
    category: 'risque-regles',
    title: 'Pourquoi mon plancher de perte maximale bouge-t-il ?',
    summary:
      'Votre plancher est réévalué à la fin de chaque journée, pas à chaque mouvement du marché. Et il ne redescend jamais.',
    status: 'publish',
    severity: 'hard_breach',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'risk engine'],
    searchAliases: [
      'eod',
      'trailing',
      'plancher',
      'floor',
      'drawdown trailing',
      'fin de journee',
      'plancher glissant',
    ],
    related: ['perte-maximale-eod', 'reset-limites-quotidiennes', 'dll-vs-perte-maximale'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: '**FIN DE JOURNÉE** (EOD) désigne le moment où votre journée est finalisée. Votre plancher de perte maximale n’est pas recalculé à chaque instant : il est réévalué une fois la journée terminée, à partir de votre meilleure clôture.',
      },
      { kind: 'visual', id: 'HLP-VIS-002' },
      { kind: 'heading', text: 'Comment il évolue' },
      {
        kind: 'list',
        items: [
          'le montant que vous pouvez perdre est fixé par vos règles ;',
          'une meilleure clôture de journée fait remonter votre plancher ;',
          'une journée moins bonne ne le fait jamais redescendre ;',
          'une fois arrivé à votre montant de départ, il s’y arrête ;',
          'le plancher affiché sur votre compte fait foi.',
        ],
      },
      {
        kind: 'paragraph',
        text: 'L’intérêt est simple : votre plancher suit vos journées terminées, pas un pic passager que le marché reprend une heure plus tard. Votre espace WARIBA affiche en permanence le plancher actuel et la marge qu’il vous reste.',
      },
    ],
  },
  {
    id: 'HLP-032',
    slug: 'reset-limites-quotidiennes',
    category: 'risque-regles',
    title: 'Quand les limites quotidiennes sont-elles réinitialisées ?',
    summary:
      'À heure fixe, la même pour tout le monde. Recharger la page ne débloque jamais un compte.',
    status: 'dynamic',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['risk engine', 'domain code'],
    searchAliases: [
      'reset',
      'minuit',
      'utc',
      'heure',
      'debloquer',
      'journee',
      'quand je peux retrader',
    ],
    related: ['perte-quotidienne', 'permissions-de-trading'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'La journée WARIBA change à heure fixe, identique pour tous les comptes. L’heure de votre prochain reset est affichée sur votre compte, dans votre fuseau horaire.',
      },
      {
        kind: 'callout',
        tone: 'attention',
        title: 'Recharger ne débloque rien',
        text: 'Après un blocage, vous pourrez de nouveau trader au prochain reset, si aucune autre règle ne s’y oppose. Rafraîchir la page ne change rien.',
      },
      {
        kind: 'paragraph',
        text: 'C’est aussi pourquoi l’interface n’affiche jamais « minuit » sans contexte : minuit chez vous et la frontière de journée du programme ne sont pas nécessairement le même instant.',
      },
    ],
  },
  {
    id: 'HLP-033',
    slug: 'permissions-de-trading',
    category: 'risque-regles',
    title: 'Comment les permissions de trading sont-elles décidées ?',
    summary:
      'WARIBA dit précisément ce que vous avez le droit de faire à chaque instant. WariX ne le devine jamais à partir de ce qui est affiché.',
    status: 'publish',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['risk engine', 'domain code'],
    searchAliases: ['permission', 'autorise', 'bloque', 'interdit', 'droits'],
    related: ['perte-quotidienne', 'ordre-refuse', 'warix-deconnexion'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'À chaque instant, WARIBA sait exactement ce que vous avez le droit de faire sur votre compte — et ce n’est pas un simple interrupteur ouvert ou fermé.',
      },
      { kind: 'visual', id: 'HLP-VIS-017' },
      { kind: 'heading', text: 'Ce que WARIBA autorise, action par action' },
      {
        kind: 'list',
        items: [
          'ouvrir une position ;',
          'agrandir une position ;',
          'réduire ;',
          'clôturer ;',
          'placer un ordre en attente ;',
          'annuler un ordre en attente.',
        ],
      },
      {
        kind: 'example',
        title: 'Pourquoi ces permissions ne sont pas un seul interrupteur',
        lines: [
          'pendant un blocage quotidien, ouvrir une nouvelle position est interdit ;',
          'clôturer une position, ce qui réduit le risque, peut rester permis.',
        ],
        conclusion:
          'Un unique état « bloqué » vous empêcherait de sortir d’une position au moment où c’est le plus utile.',
      },
      {
        kind: 'paragraph',
        text: 'Après une coupure, WariX récupère l’état réel de votre compte avant de réactiver les actions sensibles.',
      },
    ],
  },
  {
    id: 'HLP-034',
    slug: 'instruments-et-exposition',
    category: 'risque-regles',
    title: 'Quels instruments puis-je trader, et jusqu’à quelle taille ?',
    summary:
      'Les instruments disponibles et vos limites de taille viennent des règles de votre compte, pas d’une liste écrite à la main.',
    status: 'dynamic',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['symbol specifications', 'published_account_policy'],
    searchAliases: ['instruments', 'symboles', 'eurusd', 'xauusd', 'nas100', 'lot', 'exposition'],
    related: ['frais-de-trading', 'ordre-refuse', 'placer-un-ordre'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'Le périmètre V1 actuellement verrouillé comprend EURUSD, GBPUSD, USDJPY, XAUUSD et NAS100.',
      },
      { kind: 'heading', text: 'Ce qui est publié pour chaque instrument' },
      {
        kind: 'list',
        items: [
          'précision de prix ;',
          'taille minimale ;',
          'taille de contrat ;',
          'heures de marché ;',
          'taille maximale par position et au total ;',
          'spread, commission et swap applicables.',
        ],
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Ces valeurs ne sont pas recopiées ici',
        text: 'Elles vivent dans les spécifications de symboles publiées et sont affichées dans WariX pour l’instrument sélectionné. Une valeur encore candidate n’est pas affichée comme règle publique.',
      },
    ],
  },
  {
    id: 'HLP-035',
    slug: 'frais-de-trading',
    category: 'risque-regles',
    title: 'Spread, slippage, commissions : qu’est-ce qui me coûte quelque chose ?',
    summary: 'Quatre éléments qui pèsent sur vos gains et vos pertes — et donc sur votre risque.',
    status: 'dynamic',
    severity: 'information',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['symbol specifications'],
    searchAliases: ['spread', 'slippage', 'commission', 'swap', 'frais', 'cout'],
    related: ['instruments-et-exposition', 'stop-loss-take-profit', 'solde-et-equity'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'table',
        columns: ['Élément', 'Ce que c’est'],
        rows: [
          ['Spread', 'Écart entre prix acheteur et prix vendeur.'],
          [
            'Slippage',
            'Écart possible entre le prix que vous voyez et le prix auquel votre ordre est réellement exécuté.',
          ],
          ['Commission', 'Frais de transaction lorsque la spécification en prévoit.'],
          [
            'Swap',
            'Ajustement lié au maintien de certaines positions, selon l’instrument et le modèle.',
          ],
        ],
      },
      {
        kind: 'callout',
        tone: 'attention',
        title: 'Ils comptent dans le risque',
        text: 'Ces éléments modifient vos gains et vos pertes, donc l’equity que vos limites surveillent. Les montants exacts sont ceux publiés avec chaque instrument : WARIBA n’affiche jamais des frais nuls par défaut.',
      },
    ],
  },
  {
    id: 'HLP-036',
    slug: 'ordre-refuse',
    category: 'risque-regles',
    title: 'Pourquoi un ordre peut-il être refusé ?',
    summary:
      'Un refus veut dire que WARIBA n’a pas accepté l’ordre. Rien n’est exécuté et aucune position ne bouge.',
    status: 'publish',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['risk engine', 'domain code'],
    searchAliases: [
      'refuse',
      'rejected',
      'rejet',
      'erreur ordre',
      'impossible',
      'ordre bloque',
      'ne passe pas',
    ],
    related: ['permissions-de-trading', 'donnees-de-marche', 'placer-un-ordre'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'Un refus veut dire que WARIBA n’a pas accepté l’ordre. Rien n’est exécuté, aucune position ne bouge, et votre solde ne change pas.',
      },
      { kind: 'visual', id: 'HLP-VIS-015' },
      { kind: 'heading', text: 'Raisons possibles' },
      {
        kind: 'list',
        items: [
          'compte sur lequel vous ne pouvez pas trader ;',
          'perte quotidienne atteinte ;',
          'perte maximale dépassée ;',
          'taille maximale déjà atteinte ;',
          'prix trop ancien pour exécuter ;',
          'marché fermé ;',
          'ordre invalide ;',
          'connexion pas encore resynchronisée ;',
          'ressource non autorisée.',
        ],
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Un refus ne laisse aucune trace financière',
        text: 'Un ordre refusé n’est pas exécuté, n’ouvre ni n’agrandit aucune position, et ne change pas votre solde.',
      },
      {
        kind: 'paragraph',
        text: 'Quand un refus demande une action de votre part, WariX affiche un message qui reste à l’écran, avec le motif exact. Lisez-le plutôt que de renvoyer le même ordre plusieurs fois.',
      },
    ],
  },
  {
    id: 'HLP-037',
    slug: 'donnees-de-marche',
    category: 'risque-regles',
    title: 'Pourquoi WARIBA refuse-t-il d’ouvrir une position « prix trop ancien » ?',
    summary:
      'Quand les prix ne sont plus assez récents, WARIBA refuse d’ouvrir une position plutôt que de vous exécuter à un prix dépassé.',
    status: 'publish',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['domain code', 'realtime service'],
    searchAliases: [
      'stale',
      'offline',
      'deconnecte',
      'prix',
      'obsolete',
      'resync',
      'prix trop ancien',
      'pas de prix',
    ],
    related: ['warix-deconnexion', 'graphique-et-execution', 'ordre-refuse'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'table',
        columns: ['État', 'Ce qu’il signifie'],
        rows: [
          ['À jour', 'Les prix sont suffisamment récents pour exécuter.'],
          ['Prix trop anciens', 'Les prix ne sont plus assez récents pour ouvrir une position.'],
          ['Hors ligne', 'La connexion au flux est perdue.'],
          [
            'Resynchronisation',
            'WariX redemande l’état réel de votre compte avant de réactiver les actions.',
          ],
        ],
      },
      {
        kind: 'paragraph',
        text: 'Après une reconnexion, WariX ne repart jamais de ce qu’il savait avant la coupure. Il redemande l’état réel de votre compte avant de réactiver les commandes.',
      },
    ],
  },
  {
    id: 'HLP-038',
    slug: 'pratiques-autorisees-et-interdites',
    category: 'risque-regles',
    title: 'Qu’ai-je le droit de faire, et qu’est-ce qui est interdit ?',
    summary:
      'Publié seulement quand chaque pratique aura sa définition, ses critères de preuve et son recours.',
    status: 'draft_policy',
    blockedBy: 'Définitions d’intégrité (hedging, EA, HFT, copy trading) — non publiées',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy'],
    searchAliases: ['interdit', 'autorise', 'hedging', 'ea', 'bot', 'hft', 'copy trading'],
    related: ['trading-integre'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'Cet article sera publié lorsque les règles de compte définira précisément chaque pratique : définition, critère de preuve, conséquence et parcours de recours.',
      },
      {
        kind: 'paragraph',
        text: 'WARIBA ne recopiera pas les interdictions d’un concurrent. Une interdiction sans définition mesurable et sans recours est une décision arbitraire en attente.',
      },
    ],
  },
  {
    id: 'HLP-039',
    slug: 'trading-integre',
    category: 'risque-regles',
    title: 'Que se passe-t-il si WARIBA soupçonne un comportement anormal ?',
    summary:
      'Une décision d’intégrité s’appuie sur une règle publiée et des faits audités — jamais sur une impression.',
    status: 'publish',
    severity: 'operational',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'Decision Log'],
    searchAliases: ['integrite', 'fraude', 'exploitation', 'bug', 'triche'],
    related: ['lire-preuve-breach', 'ouvrir-une-contestation'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'WARIBA évalue le comportement de trading dans un environnement simulé. Une performance obtenue en exploitant volontairement une erreur technique, une donnée manifestement incorrecte ou une incohérence du système peut faire l’objet d’une revue d’intégrité lorsque les règles le prévoient.',
      },
      { kind: 'heading', text: 'Sur quoi une telle décision doit s’appuyer' },
      {
        kind: 'list',
        items: [
          'une règle publiée ;',
          'des faits ;',
          'une période ;',
          'des références d’audit ;',
          'un motif précis ;',
          'un recours lorsque la décision est contestable.',
        ],
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Une stratégie inhabituelle n’est pas une preuve',
        text: 'Trader différemment de la moyenne n’est pas, en soi, un indice de fraude. Une décision d’intégrité opaque n’en est pas une.',
      },
    ],
  },
  {
    id: 'HLP-040',
    slug: 'lire-preuve-breach',
    category: 'risque-regles',
    title: 'Comment comprendre pourquoi mon compte a été terminé ?',
    summary:
      'Ce que WARIBA vous montre pour justifier la décision, et pourquoi rien n’est effacé si vous la contestez.',
    status: 'publish',
    severity: 'hard_breach',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['risk engine', 'audit trail'],
    searchAliases: ['preuve', 'evidence', 'breach', 'justificatif', 'pourquoi'],
    related: ['limite-maximale-depassee', 'ouvrir-une-contestation', 'preuve-originale-conservee'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'Quand WARIBA met fin à un compte, la décision n’est jamais un simple verdict : vous pouvez consulter exactement ce sur quoi elle s’appuie.',
      },
      { kind: 'visual', id: 'HLP-SCR-005' },
      { kind: 'heading', text: 'Ce que vous pouvez consulter' },
      {
        kind: 'list',
        items: [
          'la règle ;',
          'le seuil ;',
          'la valeur observée ;',
          'l’instant ;',
          'la version des règles ;',
          'le compte ;',
          'les ordres et exécutions pertinents ;',
          'les données de marché utilisées ;',
          'la référence technique affichée avec l’erreur.',
        ],
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'La preuve originale est conservée',
        text: 'Une contestation ajoute un dossier et une décision. Elle ne supprime ni ne réécrit silencieusement l’événement initial.',
      },
    ],
  },
];
