import type { HelpArticle } from './types';

/**
 * WARIBA ONE — the evaluation's rules.
 *
 * Every live rule value in this category comes from `ruleTable` blocks or
 * `{{fact:…}}` tokens, both of which read the published policy. Numbers appear
 * in prose only inside `example` blocks, which the renderer labels as
 * illustrations.
 */
export const WARIBA_ONE_ARTICLES: readonly HelpArticle[] = [
  {
    id: 'HLP-010',
    slug: 'regles-essentielles',
    category: 'wariba-one',
    title: 'Les règles essentielles avant votre premier trade',
    summary:
      'Ce qui bloque aujourd’hui, ce qui termine le compte, et ce qui bloque seulement la réussite — sur une page.',
    status: 'publish',
    severity: 'information',
    audience: ['evaluation'],
    sourceOfTruth: ['published_account_policy', 'Decision Log'],
    searchAliases: ['regles', 'essentiel', 'avant de trader', 'resume', 'rules'],
    related: [
      'objectif-de-profit',
      'perte-quotidienne',
      'perte-maximale-eod',
      'meilleur-jour',
      'dll-vs-perte-maximale',
    ],
    lastReviewedAt: '2026-08-24',
    pinned: true,
    body: [
      {
        kind: 'paragraph',
        text: 'Voici les règles WARIBA ONE actuellement publiées. Un compte déjà activé garde la version acceptée le jour de son activation : celle qui s’applique au vôtre est affichée dans votre espace WARIBA.',
      },
      { kind: 'visual', id: 'HLP-VIS-019' },
      {
        kind: 'ruleTable',
        caption: 'Règles WARIBA ONE en vigueur',
        facts: [
          'profitTargetRate',
          'dailyLossRate',
          'maximumLossRate',
          'bestDayMaxRatio',
          'minimumTradingDays',
          'shortDurationSeconds',
          'activationFee',
          'evaluationPolicyVersion',
        ],
      },
      { kind: 'heading', text: 'Trois familles, trois conséquences' },
      {
        kind: 'table',
        caption: 'La distinction qui coûte le plus cher quand elle est mal comprise',
        columns: ['Ce qui se passe', 'Règle', 'Effet'],
        rows: [
          ['Bloque votre journée', 'Perte quotidienne', 'Vous reprenez au prochain reset.'],
          [
            'Termine le compte',
            'Perte maximale',
            'État terminal. Le compte ne redevient pas actif.',
          ],
          [
            'Bloque seulement la réussite',
            'Règle du Meilleur Jour',
            'Vous continuez à trader jusqu’à ce que la répartition passe.',
          ],
        ],
      },
      { kind: 'heading', text: 'À retenir' },
      {
        kind: 'list',
        items: [
          'La perte quotidienne arrête votre journée. La perte maximale met fin au compte.',
          'Règle du Meilleur Jour ≠ compte perdu.',
          'Atteindre l’objectif ne crée pas immédiatement votre compte Performance.',
          'Les positions et ordres bloquants doivent être résolus avant la validation finale.',
          'C’est toujours WARIBA qui décide si une action de trading est autorisée.',
        ],
      },
      {
        kind: 'callout',
        tone: 'attention',
        title: 'Profit rapide et profit éligible',
        text: 'Un trade profitable dont la durée est inférieure au seuil publié peut contribuer pour zéro au profit du programme. Les pertes, elles, restent toujours comptées.',
      },
    ],
  },
  {
    id: 'HLP-011',
    slug: 'objectif-de-profit',
    category: 'wariba-one',
    title: 'Comment atteindre mon objectif de profit ?',
    summary:
      'L’objectif se mesure en profit net réalisé. Un gain sur une position encore ouverte ne compte pas, et atteindre l’objectif ne crée pas immédiatement votre compte Performance.',
    status: 'publish',
    severity: 'pass_condition',
    audience: ['evaluation'],
    sourceOfTruth: ['published_account_policy'],
    searchAliases: [
      'objectif',
      'target',
      'profit target',
      '10%',
      'reussir',
      'passer',
      'valider',
      '10',
    ],
    related: ['solde-et-equity', 'objectif-atteint', 'profit-court-terme'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'WARIBA ONE demande actuellement {{fact:profitTargetRate}} de profit **réalisé**.',
      },
      {
        kind: 'example',
        title: 'Illustration sur un nominal de 10 000 USD',
        lines: [
          'objectif pédagogique : 1 000 USD de profit net réalisé ;',
          'un gain de 1 200 USD sur une position encore ouverte : ne compte pas ;',
          'ce même profit une fois la position clôturée : compte, sous réserve des règles d’éligibilité.',
        ],
        conclusion:
          'Votre propre objectif est calculé sur le nominal de votre compte, pas sur cet exemple.',
      },
      {
        kind: 'paragraph',
        text: 'WARIBA vérifie vos gains réalisés **et** toutes les autres conditions. Lorsque l’objectif est atteint, le compte passe en « Réussite en vérification » puis attend la finalisation de journée et les contrôles.',
      },
      { kind: 'heading', text: 'En revanche' },
      {
        kind: 'list',
        items: [
          'atteindre l’objectif ne désactive aucune autre règle ;',
          'le navigateur ne décide pas que vous avez réussi ;',
          'un nouvel essai n’ouvre jamais deux comptes Performance.',
        ],
      },
    ],
  },
  {
    id: 'HLP-012',
    slug: 'perte-quotidienne',
    category: 'wariba-one',
    title: 'Comment fonctionne la perte quotidienne ?',
    summary:
      'Une protection temporaire. Atteinte, elle vous empêche d’ouvrir de nouvelles positions jusqu’au prochain reset. Votre compte n’est pas perdu.',
    status: 'publish',
    severity: 'soft_lock',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'risk engine'],
    searchAliases: [
      'dll',
      'daily loss',
      'perte journaliere',
      'bloque',
      'soft lock',
      '3%',
      'daily drawdown',
      'perte du jour',
      'limite jour',
      'drawdown journalier',
      'stop journalier',
    ],
    related: ['dll-vs-perte-maximale', 'reset-limites-quotidiennes', 'permissions-de-trading'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'La perte quotidienne est une protection temporaire. Le montant de référence correspond à {{fact:dailyLossRate}} du nominal simulé, selon les règles attachées à votre compte.',
      },
      { kind: 'visual', id: 'HLP-VIS-003' },
      {
        kind: 'example',
        title: 'Illustration sur un nominal de 10 000 USD',
        lines: ['3 % de 10 000 USD représentent 300 USD de marge quotidienne.'],
        conclusion:
          'Le montant réellement applicable est celui que le Hub affiche pour votre compte.',
      },
      {
        kind: 'paragraph',
        text: 'WARIBA suit votre limite du jour en continu, positions ouvertes comprises lorsque la règle le prévoit. Si le seuil est atteint, le compte passe en **blocage quotidien**.',
      },
      { kind: 'heading', text: 'Conséquence' },
      {
        kind: 'list',
        items: [
          'vous ne pouvez plus ouvrir de nouvelle position ;',
          'réduire ou fermer une position reste souvent possible ;',
          'annuler un ordre en attente peut rester autorisé ;',
          'l’heure exacte du prochain reset est affichée sur votre compte.',
        ],
      },
      { kind: 'heading', text: 'Quand a lieu le reset' },
      {
        kind: 'paragraph',
        text: 'Le reset a lieu à **00:00 UTC**, pas à minuit chez vous. Selon votre fuseau, votre journée de trading peut donc repartir en pleine après-midi ou la veille au soir. Le compte à rebours affiché dans votre espace WARIBA est celui qui fait foi.',
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Ce n’est pas un échec définitif',
        text: 'Un blocage quotidien ne met pas fin à votre compte. Vous pourrez de nouveau trader au prochain reset, si aucune autre limite n’a été dépassée entre-temps.',
      },
    ],
  },
  {
    id: 'HLP-013',
    slug: 'perte-maximale-eod',
    category: 'wariba-one',
    title: 'Comment fonctionne la perte maximale glissante ?',
    summary:
      'Un plancher recalculé à la clôture de chaque journée. Il monte si vous terminez plus haut que jamais, ne redescend pas, et le franchir met fin au compte.',
    status: 'publish',
    severity: 'hard_breach',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'risk engine'],
    searchAliases: [
      'mll',
      'max loss',
      'drawdown',
      'trailing',
      'eod',
      'plancher',
      'breach',
      '10%',
      'maximum loss',
      'perte max',
      'compte perdu',
      'compte termine',
    ],
    related: ['trailing-eod', 'lire-preuve-breach', 'limite-maximale-depassee'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'La perte maximale protège votre compte sur toute sa durée. Elle retire {{fact:maximumLossRate}} du montant nominal, et le plancher qu’elle fixe est **glissant** : il peut monter à la fin d’une journée, jamais redescendre.',
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Ce que veut dire « EOD »',
        text: 'EOD signifie « fin de journée ». Votre plancher n’est pas recalculé à chaque instant : il est réévalué une seule fois par jour, à la clôture, à partir de votre plus haut solde de fin de journée depuis l’ouverture du compte. Un pic en cours de séance ne compte pas — seul le solde au moment de la clôture est retenu.',
      },
      {
        kind: 'example',
        title: 'Sur un compte de 10 000 USD',
        lines: [
          'au départ, votre plancher est à 9 000 ;',
          'vous terminez une journée à 10 500 : votre plancher monte à 9 500 ;',
          'la journée suivante finit plus bas : votre plancher reste à 9 500 ;',
          'vous terminez plus tard à 11 200 : votre plancher s’arrête à 10 000, votre montant de départ.',
        ],
        conclusion:
          'Le plancher qui s’applique à votre compte est affiché dans votre espace WARIBA. Ne le recalculez pas à partir de cet exemple.',
      },
      {
        kind: 'paragraph',
        text: 'Le montant retiré ne change jamais : c’est toujours {{fact:maximumLossRate}} du nominal de départ, pas un pourcentage de votre solde du moment. Et le plancher s’arrête à votre montant de départ — une fois qu’il l’atteint, il ne monte pas au-delà, quel que soit votre profit.',
      },
      {
        kind: 'callout',
        tone: 'danger',
        title: 'Conséquence',
        text: 'Si votre equity — solde plus positions ouvertes — passe sous ce plancher, le compte est terminé. C’est définitif pour ce compte.',
      },
      {
        kind: 'paragraph',
        text: 'Le compte reste consultable. Vous y retrouvez la règle concernée, le seuil, la valeur atteinte, l’heure exacte et les éléments sur lesquels la décision s’appuie.',
      },
    ],
  },
  {
    id: 'HLP-014',
    slug: 'meilleur-jour',
    category: 'wariba-one',
    title: 'Comment fonctionne la règle du Meilleur Jour ?',
    summary:
      'Elle vérifie que vos gains ne viennent pas tous d’une seule journée. Un dépassement retarde votre réussite — il ne fait jamais perdre le compte.',
    status: 'publish',
    severity: 'pass_condition',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy'],
    searchAliases: [
      'best day',
      'meilleur jour',
      'consistance',
      'consistency',
      '50%',
      'concentration',
      'repartition',
    ],
    related: ['objectif-de-profit', 'meilleur-jour-performance', 'regles-essentielles'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'La règle du Meilleur Jour vérifie que vos gains ne viennent pas tous d’une seule journée. Votre meilleure journée ne doit pas représenter plus de {{fact:bestDayMaxRatio}} de l’ensemble de vos journées gagnantes.',
      },
      { kind: 'visual', id: 'HLP-VIS-004' },
      {
        kind: 'formula',
        expression: 'part = votre meilleure journée ÷ total de vos journées gagnantes',
        caption: 'Les deux montants ne comptent que vos journées gagnantes.',
      },
      {
        kind: 'example',
        title: 'Illustration',
        lines: [
          'meilleur jour : 500 USD ;',
          'total de vos journées gagnantes : 800 USD ;',
          'votre meilleure journée pèse 62,5 % du total.',
        ],
        conclusion:
          'C’est trop concentré. Si votre meilleure journée reste à 500 USD, il vous faut atteindre 1 000 USD au total — soit 200 USD de gains sur d’autres journées.',
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Un dépassement ne termine jamais le compte',
        text: 'Vous continuez à trader jusqu’à satisfaire la condition, sous réserve des autres règles.',
      },
    ],
  },
  {
    id: 'HLP-015',
    slug: 'profit-court-terme',
    category: 'wariba-one',
    title: 'Pourquoi certains gains ne comptent-ils pas pour mon objectif ?',
    summary:
      'Un trade profitable trop court peut contribuer pour zéro au profit du programme. Les pertes, elles, sont toujours comptées.',
    status: 'publish',
    severity: 'pass_condition',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'domain code'],
    searchAliases: [
      '60 secondes',
      'scalping',
      'eligible',
      'ineligible',
      'duree',
      'court',
      'profit non compte',
      'gain non compte',
    ],
    related: ['objectif-de-profit', 'profit-eligible', 'solde-et-equity'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'Les règles en vigueur prévoient une durée minimale de {{fact:shortDurationSeconds}} pour qu’un résultat profitable contribue au résultat programme éligible.',
      },
      { kind: 'visual', id: 'HLP-VIS-005' },
      { kind: 'heading', text: 'Concrètement' },
      {
        kind: 'paragraph',
        text: 'Un trade peut être fermé avec un gain, apparaître dans votre Journal, et pourtant ne rien apporter à votre objectif si sa durée est trop courte.',
      },
      {
        kind: 'callout',
        tone: 'attention',
        title: 'Asymétrie assumée',
        text: 'Les pertes restent toujours comptées. La règle limite la contribution d’un profit très court ; elle n’efface aucune perte.',
      },
      {
        kind: 'paragraph',
        text: 'WARIBA affiche donc séparément le gain du trade, ce qu’il apporte à votre objectif, et pourquoi il n’apporte rien le cas échéant. Vous n’avez jamais à le deviner.',
      },
    ],
  },
  {
    id: 'HLP-016',
    slug: 'nombre-minimum-de-jours',
    category: 'wariba-one',
    title: 'Y a-t-il un nombre minimum de jours ?',
    summary:
      'WARIBA ONE n’impose aucune attente artificielle. Cela ne veut pas dire que la validation est immédiate.',
    status: 'publish',
    severity: 'pass_condition',
    audience: ['evaluation'],
    sourceOfTruth: ['published_account_policy'],
    searchAliases: ['jours minimum', 'minimum trading days', 'combien de jours', 'rapidite'],
    related: ['objectif-atteint', 'performance-days', 'regles-essentielles'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'ruleTable',
        caption: 'Règles WARIBA ONE en vigueur',
        facts: ['minimumTradingDays'],
      },
      {
        kind: 'paragraph',
        text: 'Il n’y a donc aucune attente imposée pour son propre compte. Toutes les autres conditions restent à remplir : profit réalisé, limites de risque, règle du Meilleur Jour, aucun dépassement, et la vérification finale.',
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'WARIBA Performance suit une autre logique',
        text: 'Chaque payout exige des journées de performance nouvelles. Voir « Comment fonctionnent les Performance Days ? ».',
      },
    ],
  },
  {
    id: 'HLP-017',
    slug: 'duree-et-inactivite',
    category: 'wariba-one',
    title: 'Ai-je une limite de temps pour réussir mon évaluation ?',
    summary:
      'WARIBA ONE n’a pas de limite de temps fixe pour atteindre l’objectif. Un compte peut néanmoins devenir inactif.',
    status: 'publish',
    severity: 'operational',
    audience: ['evaluation'],
    sourceOfTruth: ['published_account_policy', 'Decision Log'],
    searchAliases: ['duree', 'delai', 'inactivite', 'inactif', 'expiration', 'temps'],
    related: ['nombre-minimum-de-jours', 'contacter-le-support'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'WARIBA ONE n’impose pas de limite de temps fixe pour atteindre l’objectif.',
      },
      {
        kind: 'paragraph',
        text: 'Un compte peut passer à l’état **inactif**. Ce n’est pas la même chose qu’une limite maximale dépassée : votre compte n’est pas perdu, et l’écran indique ce que vous pouvez encore faire.',
      },
      {
        kind: 'callout',
        tone: 'attention',
        title: 'Aucun compte à rebours n’est publié ici',
        text: 'Les règles en vigueur ne fixent aujourd’hui aucun délai d’inactivité, et cet article n’en invente pas un. Le statut réel de votre compte, et lui seul, fait foi. Si votre compte affiche « Inactif », ouvrez une demande pour connaître vos options.',
      },
    ],
  },
  {
    id: 'HLP-018',
    slug: 'position-pendant-la-nuit',
    category: 'wariba-one',
    title: 'Puis-je garder une position pendant la nuit ?',
    summary: 'La décision produit en vigueur est celle qui s’applique aujourd’hui à votre compte.',
    status: 'dynamic',
    severity: 'information',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'Decision Log'],
    searchAliases: ['overnight', 'nuit', 'garder position', 'swap'],
    related: ['position-pendant-le-week-end', 'frais-de-trading'],
    lastReviewedAt: '2026-08-24',
    body: [
      { kind: 'ruleTable', caption: 'Règles en vigueur', facts: ['overnightAllowed'] },
      {
        kind: 'paragraph',
        text: 'Une position conservée pendant la nuit reste soumise à la perte quotidienne, à la perte maximale, aux spreads, aux swaps lorsqu’ils existent, aux gaps et interruptions de marché, et aux permissions du compte.',
      },
      {
        kind: 'callout',
        tone: 'attention',
        title: '« Autorisée » ne veut pas dire « sans risque »',
        text: 'Un écart de prix à l’ouverture peut franchir votre plancher pendant que vous dormez. La règle vous autorise à garder la position ; elle ne la protège pas.',
      },
    ],
  },
  {
    id: 'HLP-019',
    slug: 'position-pendant-le-week-end',
    category: 'wariba-one',
    title: 'Puis-je garder une position pendant le week-end ?',
    summary: 'La décision produit en vigueur est celle qui s’applique aujourd’hui à votre compte.',
    status: 'dynamic',
    severity: 'information',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['published_account_policy', 'symbol specifications'],
    searchAliases: ['weekend', 'week-end', 'samedi', 'dimanche', 'cutoff'],
    related: ['position-pendant-la-nuit', 'instruments-et-exposition'],
    lastReviewedAt: '2026-08-24',
    body: [
      { kind: 'ruleTable', caption: 'Règles en vigueur', facts: ['weekendAllowed'] },
      {
        kind: 'paragraph',
        text: 'L’heure de coupure dépend de l’instrument. Consultez toujours l’heure affichée pour l’instrument concerné et le fuseau associé plutôt qu’une heure générique.',
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Aucune heure générique dans cet article',
        text: 'Une heure de cutoff écrite ici serait fausse pour au moins un instrument. Elle est publiée avec la spécification de chaque symbole.',
      },
    ],
  },
  {
    id: 'HLP-020',
    slug: 'trading-pendant-les-annonces',
    category: 'wariba-one',
    title: 'Puis-je trader pendant les annonces économiques ?',
    summary: 'La décision produit en vigueur est celle qui s’applique aujourd’hui à votre compte.',
    status: 'dynamic',
    severity: 'information',
    audience: ['evaluation'],
    sourceOfTruth: ['published_account_policy', 'Decision Log'],
    searchAliases: ['news', 'annonces', 'nfp', 'calendrier economique'],
    related: ['frais-de-trading', 'ordre-refuse'],
    lastReviewedAt: '2026-08-24',
    body: [
      { kind: 'ruleTable', caption: 'Règles WARIBA ONE en vigueur', facts: ['newsAllowed'] },
      {
        kind: 'paragraph',
        text: 'Les autres règles de risque continuent de s’appliquer et le slippage peut augmenter fortement autour d’une annonce.',
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Aucune fenêtre d’interdiction Performance n’est publiée',
        text: 'WARIBA n’annoncera de fenêtre d’interdiction que lorsque la règle et un calendrier économique fiable seront arrêtés ensemble. Aucune sanction rétroactive ne sera construite à partir d’une information qui n’était pas visible au trader.',
      },
    ],
  },
  {
    id: 'HLP-021',
    slug: 'objectif-atteint',
    category: 'wariba-one',
    title: 'Que se passe-t-il quand j’atteins l’objectif ?',
    summary:
      'Le compte passe en vérification. Les règles continuent de s’appliquer, et rien n’est activé tant que la revue n’a pas conclu.',
    status: 'publish',
    severity: 'pass_condition',
    audience: ['evaluation'],
    sourceOfTruth: ['Decision Log', 'domain code'],
    searchAliases: ['reussi', 'pass', 'pass pending', 'verification', 'objectif atteint'],
    related: ['objectif-de-profit', 'parcours-one-performance-review', 'compte-performance'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'Atteindre l’objectif ne déclenche pas immédiatement un compte Performance.',
      },
      { kind: 'visual', id: 'HLP-VIS-006' },
      {
        kind: 'formula',
        expression:
          'actif → réussite en vérification → revue de fin de journée → approuvé → Performance',
      },
      { kind: 'heading', text: 'Dès la mise en vérification' },
      {
        kind: 'list',
        items: [
          'vous ne pouvez plus ouvrir de nouvelle position ;',
          'WariX passe en lecture seule pour les actions concernées ;',
          'le Hub affiche « Réussite en vérification » ;',
          'WARIBA affiche à partir de quand la vérification peut commencer.',
        ],
      },
      {
        kind: 'paragraph',
        text: 'La vérification porte sur la journée terminée, vos règles, vos ordres et un éventuel dépassement de limite. Un cas ambigu est examiné par une personne. Une fois approuvé, votre compte Performance est créé une seule fois.',
      },
      { kind: 'visual', id: 'HLP-VIS-018' },
      {
        kind: 'callout',
        tone: 'attention',
        title: 'Les règles ne se désactivent pas',
        text: 'C’est le malentendu le plus coûteux du produit : tant que la journée n’est pas terminée, un compte qui vient d’atteindre l’objectif peut encore dépasser une limite.',
      },
    ],
  },
  {
    id: 'HLP-022',
    slug: 'limite-maximale-depassee',
    category: 'wariba-one',
    title: 'Que se passe-t-il si ma perte maximale est dépassée ?',
    summary:
      'Votre compte est terminé. Vous gardez accès à tout ce qui explique la décision, et vous pouvez la contester.',
    status: 'publish',
    severity: 'hard_breach',
    audience: ['evaluation', 'performance'],
    sourceOfTruth: ['risk engine', 'domain code'],
    searchAliases: [
      'breach',
      'echec',
      'compte termine',
      'perdu',
      'fail',
      'compte bloque',
      'compte ferme',
    ],
    related: ['perte-maximale-eod', 'lire-preuve-breach', 'ouvrir-une-contestation'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'Lorsque votre perte maximale est dépassée, le compte est terminé. Il ne redevient pas actif.',
      },
      { kind: 'heading', text: 'Ce que vous pouvez consulter' },
      {
        kind: 'list',
        items: [
          'la règle concernée ;',
          'le seuil ;',
          'la valeur observée ;',
          'l’heure ;',
          'la version des règles ;',
          'la preuve et les références disponibles.',
        ],
      },
      {
        kind: 'callout',
        tone: 'information',
        title: 'Vous avez un recours',
        text: 'Depuis le compte concerné, vous pouvez ouvrir une contestation ou contacter le support. La preuve originale n’est jamais supprimée.',
      },
    ],
  },
  {
    id: 'HLP-023',
    slug: 'reset-ou-recommencer',
    category: 'wariba-one',
    title: 'Puis-je recommencer une évaluation échouée ?',
    summary:
      'La politique commerciale de reset reste ouverte ; rien n’est publié tant qu’elle ne l’est pas.',
    status: 'draft_policy',
    blockedBy: 'Politique commerciale reset/repurchase — OPEN',
    severity: 'operational',
    audience: ['evaluation'],
    sourceOfTruth: ['Decision Log'],
    searchAliases: ['reset', 'recommencer', 'racheter', 'retry'],
    related: ['limite-maximale-depassee'],
    lastReviewedAt: '2026-08-24',
    body: [
      {
        kind: 'paragraph',
        text: 'La politique commerciale de reset/repurchase est actuellement ouverte. Tant qu’elle n’est pas verrouillée, WARIBA ne publie aucun prix de reset, aucune remise, aucun bouton « Reset maintenant » et aucune promesse de réouverture.',
      },
      {
        kind: 'paragraph',
        text: 'Un compte terminé ne sera jamais réécrit comme s’il n’avait pas échoué. Si une politique de recommencement est adoptée, elle créera une nouvelle commande et un nouveau compte avec une nouvelle piste d’audit.',
      },
    ],
  },
];
